import { cssVars, escapeHtml as esc, slugify, extUrl } from './tokens.js'
import { baseCss } from './baseCss.js'
import { mainJs } from './mainJs.js'
import { skins, headlineFonts } from './skins.js'
import { simpleNav, siteNav, footer, thankYouBody } from './blocks.js'
import { registryFor } from './sections.js'

const placeholderCss = `
.video-placeholder { display: grid; place-items: center; background: color-mix(in oklab, var(--brand) 60%, #0a0a10); }
.vp-inner { display: grid; place-items: center; gap: 14px; color: #fff; }
.vp-play { width: 74px; height: 74px; border-radius: 50%; display: grid; place-items: center; background: rgb(255 255 255 / 0.16); border: 2px solid rgb(255 255 255 / 0.6); font-size: 22px; padding-left: 5px; }
.vp-text { font-size: 14px; opacity: 0.75; letter-spacing: 0.06em; text-transform: uppercase; }
.svc-includes { list-style: none; padding: 0; margin-top: 18px; display: grid; gap: 10px; }
.svc-includes li { display: flex; gap: 10px; align-items: baseline; font-size: 15.5px; color: var(--mut); }
.svc-includes li::before { content: "—"; color: var(--accent); font-weight: 700; }
.svc-price { font-weight: 800; color: var(--brand); margin-top: 4px; }
.contact-info { display: grid; gap: 6px; margin-top: 26px; font-size: 16px; }
.contact-info a { color: var(--brand); font-weight: 600; }
.thanks-wrap { min-height: 72vh; display: grid; place-items: center; text-align: center; }
`

function fontLinks(skin, brand) {
  const params = [...skins[skin].fonts.params]
  const override = headlineFonts[brand.font]
  if (override?.param && !params.includes(override.param)) params.push(override.param)
  const href = `https://fonts.googleapis.com/css2?${params.map((p) => `family=${p}`).join('&')}&display=swap`
  return `<link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="${href}" rel="stylesheet">`
}

function shell({ title, description, body, skin, brand, inlineCss, previewScript }) {
  const css = inlineCss ? `<style>${inlineCss}</style>` : '<link rel="stylesheet" href="css/styles.css">'
  const scripts = inlineCss
    ? `<script>${mainJs}</script>${previewScript || ''}`
    : '<script src="js/main.js"></script>'
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  ${fontLinks(skin, brand)}
  ${css}
</head>
<body>
${body}
${scripts}
</body>
</html>`
}

// Give a section a background image: a .sec-bg layer with its own opacity sits
// under the content (which gets lifted above it via .has-bg in baseCss).
function injectBg(html, bg) {
  const m = html.match(/<(section|div)([^>]*)>/)
  if (!m || !bg?.image) return html
  const url = String(bg.image).replace(/["'\\\s]/g, '').replace(/&/g, '&amp;')
  const opacity = Math.min(1, Math.max(0.05, Number(bg.opacity) || 0.25))
  const rootClass = `has-bg${bg.invert ? ' bg-invert' : ''}`
  const attrs = m[2].includes('class="') ? m[2].replace('class="', `class="${rootClass} `) : `${m[2]} class="${rootClass}"`
  const layer = `<div class="sec-bg" style="background-image:url('${url}');opacity:${opacity}" aria-hidden="true"></div>`
  return html.replace(m[0], `<${m[1]}${attrs}>${layer}`)
}

// Render a page's visible sections in layout order. Each section's root
// element gets data-sec="<key>" so the preview can map clicks back to the
// matching editor group (stripped from exports).
function renderSections(layout, registry, ctx) {
  return layout
    .filter((s) => !s.hidden && registry[s.key])
    .map((s) => injectBg(registry[s.key].render(ctx).replace(/<(section|div)\b/, `<$1 data-sec="${s.key}"`), s.bg))
    .join('\n')
}

// Inline-editing annotations are a preview affordance only.
const stripEditAttrs = (html) => html.replace(/ data-(edit|edit-rich|edit-ml|sec|buy)="[^"]*"/g, '')

const sitePages = [
  { file: 'index.html', title: 'Home' },
  { file: 'about.html', title: 'About' },
  { file: 'services.html', title: 'Services' },
  { file: 'contact.html', title: 'Contact' },
]

function buildCss(config) {
  const { brand, skin } = config
  const skinDef = skins[skin]
  const override = headlineFonts[brand.font]
  const displayFamily = override?.family || skinDef.fonts.display
  return `/* Generated by Buildrr — edit freely. Brand colors live in :root below. */
${cssVars(brand, brand.tone)}
:root {
  --font-display: ${displayFamily};
  --font-body: ${skinDef.fonts.body};
  --display-weight: ${skinDef.fonts.displayWeight};
  --display-tracking: ${skinDef.fonts.tracking};
}
${baseCss}
${placeholderCss}
/* ---- Skin: ${skinDef.name} ---- */
${skinDef.css}`
}

// The "how your forms capture emails" section, specific to the chosen destination.
function captureReadme(config) {
  const capture = config.pageType === 'optin' ? config.optin.capture : config.pageType === 'site' ? config.site.capture : null
  if (!capture) return '' // sales page sells via checkout links, no email form
  const D = capture.destination
  const head = '## Your email capture\n'
  if (D === 'netlify') {
    return `${head}This site uses **Netlify Forms**. Deploy to Netlify (drag the folder onto
https://app.netlify.com/drop) and every submission shows up under Forms in your
Netlify dashboard — turn on email notifications there, or forward to your email tool
via Netlify's Zapier/Make integration. Capture only works on Netlify; on other hosts
the form still sends visitors to thank-you.html.
`
  }
  if (D === 'kit') {
    return `${head}Submissions go to your **ConvertKit / Kit** form at:
\`${capture.actionUrl || '(set the form URL in Buildrr)'}\`
Visitors stay on your own thank-you.html. To change it, edit the form's \`action\` in the HTML.
`
  }
  if (D === 'mailchimp') {
    return `${head}Submissions go to **Mailchimp** at:
\`${capture.actionUrl || '(set the form URL in Buildrr)'}\`
Mailchimp shows its own confirmation page after signup (that's how their embedded
forms work). Edit the form's \`action\` in the HTML to change it.
`
  }
  if (D === 'mailerlite') {
    return `${head}Submissions go to **MailerLite** at:
\`${capture.actionUrl || '(set the form URL in Buildrr)'}\`
MailerLite shows its own confirmation page after signup. Edit the form's \`action\` to change it.
`
  }
  if (D === 'formsubmit') {
    return `${head}Submissions are emailed to you via **FormSubmit** (${capture.email || 'your email'}).
The first time someone submits, FormSubmit sends you a one-time confirmation email —
click it once to activate. Visitors stay on your own thank-you.html.
`
  }
  if (D === 'custom') {
    return `${head}Submissions post to your endpoint:
\`${capture.actionUrl || '(set the URL in Buildrr)'}\`
${capture.customAjax ? 'Sent in the background; visitors stay on thank-you.html.' : 'A normal form POST; the response page is whatever your endpoint returns.'}
`
  }
  return `${head}No email tool is connected yet — the form just forwards visitors to
thank-you.html. Open the **Publish** tab in Buildrr to connect ConvertKit, Mailchimp,
MailerLite, FormSubmit, Netlify Forms, or a custom endpoint.
`
}

function readme(config, pages) {
  const { brand } = config
  return `# ${brand.name} — exported from Buildrr

Plain HTML/CSS/JS. No build step, no dependencies. Upload the whole folder anywhere
that serves static files and you're live.

## Files
${pages.map((p) => `- ${p.file} — ${p.title}`).join('\n')}
- css/styles.css — all styles (brand colors are CSS variables at the top)
- js/main.js — scroll reveals, mobile nav, form handling (a few KB, no libraries)

## Deploy in one minute
- **Netlify Drop**: drag this folder onto https://app.netlify.com/drop
- **Vercel**: run \`npx vercel\` in this folder
- **Cloudflare Pages**: drag the folder into a new Pages project
- **GitHub Pages**: push to a repo, enable Pages in settings
- **Any classic host (cPanel/FTP)**: upload everything to public_html

${captureReadme(config)}
## Change colors later
Open css/styles.css — the first :root block holds --brand and --accent. Everything
derives from those two colors.
`
}

export function buildFiles(config, { preview = false, previewScript = '' } = {}) {
  const { pageType, brand } = config
  const css = buildCss(config)
  const wrap = (title, description, body) =>
    shell({ title, description, body, skin: config.skin, brand, inlineCss: preview ? css : null, previewScript: preview ? previewScript : '' })

  let pages = []
  const files = {}

  if (pageType === 'optin') {
    const d = config.optin
    pages = [
      { file: 'index.html', title: 'Opt-in' },
      { file: 'thank-you.html', title: 'Thank you' },
    ]
    const body = `
${simpleNav(brand, d.hero.ctaLabel, '#signup')}
<main>
${renderSections(d._layout, registryFor('optin'), { d, brand })}
</main>
${footer(brand, d.settings.footerNote)}`
    files['index.html'] = wrap(`${brand.name} — ${d.hero.eyebrow}`, d.hero.subhead.slice(0, 155), body)
    files['thank-you.html'] = wrap(
      `You're in — ${brand.name}`,
      'Check your inbox.',
      thankYouBody(brand, 'You’re in. Check your inbox.', 'Your first lesson is on its way. If it’s not there in two minutes, peek at your spam folder and drag it to your inbox.', 'index.html')
    )
  } else if (pageType === 'sales') {
    const d = config.sales
    pages = [{ file: 'index.html', title: 'Sales page' }]
    // Buy buttons scroll to the offer box by default; "directCta" (or a
    // hidden/removed offer section) sends them straight to the checkout link.
    const offerVisible = d._layout.some((s) => s.key === 'offer' && !s.hidden)
    const checkout = extUrl(d.offer.checkoutUrl)
    const buyHref = d.settings.directCta && checkout ? checkout : offerVisible ? '#offer' : checkout || '#'
    const body = `
${simpleNav(brand, d.hero.ctaLabel, buyHref, null, ` data-buy="${checkout ? 'ok' : 'missing'}"`)}
<main>
${renderSections(d._layout, registryFor('sales'), { d, brand, buyHref })}
</main>
${footer(brand, d.settings.footerNote)}`
    files['index.html'] = wrap(`${brand.name} — ${d.hero.headline.replace(/\*/g, '')}`, d.hero.subhead.slice(0, 155), body)
  } else {
    const d = config.site
    pages = [...sitePages, { file: 'thank-you.html', title: 'Thank you' }]
    const pageMeta = {
      'index.html': { key: 'home', title: `${brand.name} — ${d.global.tagline}`, desc: d.home.hero.subhead },
      'about.html': { key: 'about', title: `About — ${brand.name}`, desc: d.about.hero.subhead },
      'services.html': { key: 'services', title: `Services — ${brand.name}`, desc: d.services.hero.subhead },
      'contact.html': { key: 'contact', title: `Contact — ${brand.name}`, desc: d.contact.hero.subhead },
    }
    for (const [file, meta] of Object.entries(pageMeta)) {
      const body = `
${siteNav(brand, sitePages, file, d.global.ctaLabel)}
<main>
${renderSections(d._layout[meta.key], registryFor('site', meta.key), { d, brand })}
</main>
${footer(brand, d.settings.footerNote)}`
      files[file] = wrap(meta.title, meta.desc.slice(0, 155), body)
    }
    files['thank-you.html'] = wrap(
      `Thanks — ${brand.name}`,
      'Message received.',
      thankYouBody(brand, 'Got it. Talk soon.', 'Your message is in our inbox and we reply to every note within one business day.', 'index.html')
    )
  }

  if (!preview) {
    for (const key of Object.keys(files)) files[key] = stripEditAttrs(files[key])
  }

  files['css/styles.css'] = css
  files['js/main.js'] = mainJs
  if (!preview) files['README.md'] = readme(config, pages)

  return { files, pages, zipName: `${slugify(brand.name)}-${pageType}` }
}
